//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoKystova
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public int id_material_type { get; set; }
        public string type { get; set; }
        public float percent_defect { get; set; }
    }
}
