//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoKystova
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProduct
    {
        public int id_partner_product { get; set; }
        public int quantity { get; set; }
        public System.DateTime date { get; set; }
        public int id_product { get; set; }
        public int id_partner { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Product Product { get; set; }
    }
}
